name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t devops-challenge-app .

      - name: Deploy Docker Container
        run: |
          docker run -d -p 80:3000 devops-challenge-app
